language: go
services:
- docker
go:
- '1.9'
branches:
  only:
  - master
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: hgJ18j3RJa4+nY+SH6CpOtv+M57zX0CHD+Q4KlSIKlPo7ZaYNuTEl0YIWfqVEQ+faob347Gs3cb/7flciIa47lcI1RDqQPKHvv2rIEafTqkrUIXHdBn5OfeDXDz9uKB146ruytEZ6Bnl3f4RECwBN2e6ncywZjQufAiM/eoID2d1lPz8Gu1kyRnFxiX4swyp4AKBpZvKN28nKjqJ/bJhv+zT+s+uLh9OyftDglSXuNZ4qmqBAQHbmrQPqbhx6LD2i3eZXUUsibNJTfckbMKadbxX6CYRENAVwgU+lGVZZiChUYOc+3T7uhIDQh9tIDQPPiewaTqDeBfkwsNF9jSrBACtWBiMG9A8RVhScDAE08RhtZN7j2XxRgWbkj4hTzgPPRhVS/yCb0K4GbFQgiMyxJEztaMPjTwcpU/b7FbOS91t8ikuhwqFMBjjdpiv+ARn6AoYKAgcR3XLKhH9qntoDqL2YteovuO3wsEa+fZCjfYbXoJE3T4+yG4IgXb7VA5RTLrE2OAOOtPkYzIYKFTrcBPPwquxj7mAiFCJxQSv842NBQsw+bSCy2oNfFqO4ffa/R9/eXijLZ6cN8EbpAAEkhFeOF0pjwS1P9YCvh6MXTabyKv4SUxOhX28P0GcrbxLOjH+oxqKMeHWGipQW+ElzGi0GMyc05GNbT8dKOhKnxI=
  - secure: ARZEQ9kDz15yANxaTvpwijTpjlAXa5yVq2VFt6eeoT8Gmm6d/eME+8+VDt+DiwYhhcfkWrgOFwiF3nv4YE0d+7yelcNCKQTTpETtdOv48MazSoHJVKcRaW3crpyF4mGC1Tnp6AA6s9VftANr3s5Q4SBhb/UApI6VGlRIhPY+Rc4Usrp5rcB0kc31PgVsSG1YvXPlofHvbbaBenS1oGzOb8b1ZZF8awoqUbmRNcHRtc7H02PdXfz+22hRpt/hKfjsa8cnwtM6pbUgyaeykDuRWLfNYxH+fnAlEfaYmHvW0aUQN+zKPU8u83opSXefZPHEO+HiguaexacbOl9RJUc2vmFunjSpcEjZku5SUFAKN7GNtNleVNdim5ghNjro9PqsibLfM++reY1ga9CbwOP7oT251+atv9xfAuuOZZKrnURLLXQFazj6hDub9cZ+coOs8rJ6C0AswETAK2zyNLpsIb5FLWC2MjSRL+IX+MOQ08NvFAmV2y3Xah9gQ6F4+hTOM5O60vDpgeir2YCyzwNIrwocuJiQtmvlayIwz9a2+KLo7ZNMlBWAcVq5ibwEafwG/nA91j3NkBfu4SyaEkCKkQgEA6wBAPijpPBQflUxpHPQ3rvYb4ZNAHBz1KRHBK3ULOZj1uJfx6tvG5C5Q+CEdM1z23KWnAfuMBza5AMK4CE=
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: 0Toa67ZJrxFt3nJMFuUVO4tyB32Kj8hQ3MwDqGgGvqUNUM2R1/EQJtEmHqJMqvQ9X5I4J3vnfSVr815W3y7Mh9WBkr/sgTumlDo2nLwrQAYuFVd0yimuDKmOJ5ZgQA6W7vcECQ8wqLfDOA14RPXIg//mHAgCeI5dj/SfUYq5LsmFpoJj5SndrrKp1KMIcfkPqKDws8GmCxDe5B4ztJriQmuVa8wWYlxluGhn/2r6NbaIGJ9NarcSkpbTHUkh5qv5OZD4JQ2bu6s7S/RqYpHVe52RONDjTHkec+uwcjq+rU5W7/fB91QRUAM5qDmM1sfuauTa8KsUWTKbkByKxckZnFqvaUhK8dQmr+M9RnKns7mVkGq1p+GSGi2chVKvF15cZdVsF6qO6WR1R6khkDZLbSaU5eLljIg3flFMzHsDujmuqv7TgWXeFpO99vXUKoJEbyPxEur7gZpMXAIP6IoNns3kYdVY3xkmWQIUgUouefc4kBam46zppWaHfFinZ4u0NB+Cy6XzrKbJbboi99dmL5XDgUCouVh8701z9k5rpj7NowqNE13/dooXhc76dn9cYU7SrAFgGqy0RkzKNs2Yhqhvhf8PiTQwhah9ujbygIE6QLfwhydVbZr32EBrgqVMp4JYkVK31XfeuGLkVA9Oq2pyNJg+RqvgfCgDfKk2hWg=
after_success:
- CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/xtradio-api .
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
- export REPO=xtradio/api
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:latest .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
