language: go
services:
  - docker
go:
  - '1.9'
branches:
  only:
  - master
env:
  global:
  - secure: YYH/xrFAgf8gSynm9QqQsx2PRHxJ/ZX2KTOlq0aDacRVrtP7CeCCWn9U2VqRLr0DEFsIF6gozc1mxbuZ/GMXRux2t+SS9Z8sRLGbo081etg69Ds6OLqdZGozfkUbUGDDOu4tyM8G/B15pDOSag5F86mPZr3JSI14ORWX79c6llEciS1a8WKTSLcTYSQV1XbPqgRYxoSSbTqJ6lLfybXgRUaK5wefxOiavvZrXTRfdpXSCsCkcNraRu+boYkd7z/EC5mb5GlRe+ADDkfLykKSdXHcUSk7qIPo0g9fwar3Vn2B96l5T2hgPK87qxPB+RDlg6rY8TZKm+GvGwvWS1wZnqzzCrCQg/nnUlZfMnNBmTxzNTo2I9ABqhpFMDB4wVaSuxBXYygzVEthrWDBD05YiV3oAfXMvZCZl4sFjEINFki1MmV8QzHsw+DpVd3WgtpshZHPSFsfK8hnlHD9IwHlcqMq/jzy1KPELKaIvObK1tkBA9GawRPWZmFA30O6cH5uU/jFfKE7VcIKQLWt/GqsFRVygDl26DkgN4QQV+LoZbmhhPx/bAg46LFdpIljIShWRHV+B6qf3o8ouMGXyOXKLd/EebpTc1wb21ho65MSKv+jgaX5xRj3MHBL2uk/M/nQN3x3bKz50CIyb+F9pRZ6YQcFpmK3HbXNwJOzwv1QQmA=
  - secure: XLTfPtt5RWWqpMFWCr0ZCvKLljh3DFIHoC9pghA1GlU2m4geijGB1dwABkNc26IdbgD0CxYZYxyawIRR1xq68jbn52ki9uE9IAK2EPhZvxCTVG1quM6z+lrLyKJlOB7Xkmu/saz6iopHn+Lnor2tizzQg8YgYTYYNAntkIWl7ZfcjAYYPgwhTH/7DUoKfHPtnwBlkyanrZy5XA+UCpOYzzrA+Qzier8rA5A1zyzf3Gc/eMI+sfOVZk2L65wlzVEO0l+O4febd4imO7Bd4DgaR2lbJdBgUz6r7ZeQ4ieQjfxRNN2z8mtgS0lDpswahh4SsCQWzxCbcYsgIodFvwKshfGpDS46tF+x1QufLDGq+4YEclwptsb5wVJQq8MmOTfvbmbWFVUGCtU7FOaGi8bu5qDI/fJIhuRiv6ryeiByfrt9bFK50HT2HVvQZ/hpyeJ0PO5aYRS+OSbLXE5tPyqPzspq+TH7NacPInfF8SBghrORK5qHc+ntf065B4+sWPypMW2e683r+6fMGz0VAiPcEmLsROn8i1yeUQKhsITcWwXwsi9SjN2pR9B8FYkr0phpDeMG4hoeksX+mz7yURuFiO/tmucNGuBh8WUZLNCJr9phogqnDBC2nhHDUJ0GjwmYP99V8wWCYXuJyMlxPaFlDE+e7UUNdzco44Ag5fxaZtE=
  - COMMIT=${TRAVIS_COMMIT::8}
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: 0Toa67ZJrxFt3nJMFuUVO4tyB32Kj8hQ3MwDqGgGvqUNUM2R1/EQJtEmHqJMqvQ9X5I4J3vnfSVr815W3y7Mh9WBkr/sgTumlDo2nLwrQAYuFVd0yimuDKmOJ5ZgQA6W7vcECQ8wqLfDOA14RPXIg//mHAgCeI5dj/SfUYq5LsmFpoJj5SndrrKp1KMIcfkPqKDws8GmCxDe5B4ztJriQmuVa8wWYlxluGhn/2r6NbaIGJ9NarcSkpbTHUkh5qv5OZD4JQ2bu6s7S/RqYpHVe52RONDjTHkec+uwcjq+rU5W7/fB91QRUAM5qDmM1sfuauTa8KsUWTKbkByKxckZnFqvaUhK8dQmr+M9RnKns7mVkGq1p+GSGi2chVKvF15cZdVsF6qO6WR1R6khkDZLbSaU5eLljIg3flFMzHsDujmuqv7TgWXeFpO99vXUKoJEbyPxEur7gZpMXAIP6IoNns3kYdVY3xkmWQIUgUouefc4kBam46zppWaHfFinZ4u0NB+Cy6XzrKbJbboi99dmL5XDgUCouVh8701z9k5rpj7NowqNE13/dooXhc76dn9cYU7SrAFgGqy0RkzKNs2Yhqhvhf8PiTQwhah9ujbygIE6QLfwhydVbZr32EBrgqVMp4JYkVK31XfeuGLkVA9Oq2pyNJg+RqvgfCgDfKk2hWg=
after_success:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/xtradio-api .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=xtradio/api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:latest .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
